project:
  type: book

book:
  title: "CtoPython"
  author: "David Peña Peralta"
  date: "9/9/2023"
  chapters:
    - index.qmd
    - new_rules.qmd
    - structure.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



